### ISSUE TITLE
En/Disable WiFi Using the Reset Button?

### ISSUE THREAD

**Issue by ghmia** [Torxgewinde/Desk-Lamp-Alternative-Firmware#2]
Can you do it? Thx!

BTW, the brightness and colour temperature adjustment using the rotary button is the same as the original firmware? Just as smooth?

**Comment by Torxgewinde** [comment]
Hello,
The brightness and color change works quite smooth. I spend some time on fading from cold to warm-white while keeping the overall brightness as constant as possible. Also, when adjusting brightness it will not just switch over, but fade from the original brightness to the new value within a few milliseconds which makes it a smooth impression.

Changing the functionality of the reset button is technically possible. I am just not fully convinced it is useful.

Suggestion:
- Reset pin remains as it is and reenables Wifi after resetting everything. This is what I would an reset button to do.
- Add an option to have WiFi disabled in the Wifi setup dialog. To re-enable Wifi a reset can be done.

Sound good?

**Comment by ghmia** [comment]
Yeah sounds good! Thx!

**Comment by ghmia** [comment]
Do you mean if I use the rotary to change it's basically the same as the original firmware, or better?

**Comment by ghmia** [comment]
BTW do I need to backup the original firmware in advance?

**Comment by ghmia** [comment]
Hi? : )

**Comment by 1043717432** [comment]
Hi, thanks for sharing.

I wonder if firmware can be used in other led lights?

Achieve the same effect of millet table lamp

**Comment by Torxgewinde** [comment]
A "Disable WiFi Option" will be implemented, but please be patient. Life is busy :-/

I think the XIAOMI Light is available with a couple of different names. An internet search revelaed a very similar looking light that is indeed named "millet table lamp". I can imagine it is exactly the same, but please consider it might be different as this is just an opinion.
