### ISSUE TITLE
An image of the original lamp firmware

### ISSUE THREAD

**Issue by dmsergeevich63** [Torxgewinde/Desk-Lamp-Alternative-Firmware#4]
Hello!
I want to recreate the yeelight LXV1.7 board for use as a ceiling light control box.
An esp8266 board should come to me soon, but I do not have such a lamp and therefore I would be very happy if you upload the yeelight firmware image.

**Comment by Torxgewinde** [comment]
Hi,
For me it was completely out of question to keep the original firmware. I can only recommend to use an opensource alternative that gives users the control and where the inner workings are transparent.

I leave this issue open, perhaps someone else kept the original firmware and wants to share?

Kind regards,
Tom
